TERMTXT:	MOVLW 'G'
			CALL Send_Serial

			MOVLW 'A'
			CALL Send_Serial

			MOVLW 'M'
			CALL Send_Serial

			MOVLW 'E'
			CALL Send_Serial

			MOVLW ' '
			CALL Send_Serial

			MOVLW 'O'
			CALL Send_Serial

            MOVLW 'V'
			CALL Send_Serial

            MOVLW 'E'
			CALL Send_Serial

            MOVLW 'R'
			CALL Send_Serial

			RETURN

TXTINI:     MOVLW 'U'
			CALL Send_Serial
            MOVLW 's'
			CALL Send_Serial
            MOVLW 'a'
			CALL Send_Serial
            MOVLW ' '
			CALL Send_Serial
            MOVLW 'l'
			CALL Send_Serial
            MOVLW 'a'
			CALL Send_Serial
            MOVLW 's'
			CALL Send_Serial
            MOVLW ' '
			CALL Send_Serial
            MOVLW 'f'
			CALL Send_Serial
            MOVLW 'l'
			CALL Send_Serial
            MOVLW 'e'
			CALL Send_Serial
            MOVLW 'c'
			CALL Send_Serial
            MOVLW 'h'
			CALL Send_Serial
            MOVLW 'a'
			CALL Send_Serial
            MOVLW 's'
			CALL Send_Serial
            MOVLW ' '
			CALL Send_Serial
            MOVLW 'p'
			CALL Send_Serial
            MOVLW 'a'
			CALL Send_Serial
            MOVLW 'r'
			CALL Send_Serial
            MOVLW 'a'
			CALL Send_Serial
            MOVLW ' '
			CALL Send_Serial
            MOVLW 'm'
			CALL Send_Serial
            MOVLW 'o'
			CALL Send_Serial
            MOVLW 'v'
			CALL Send_Serial
            MOVLW 'e'
			CALL Send_Serial
            MOVLW 'r'
			CALL Send_Serial
            RETURN


			


			
